name: Generate News Video

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: base
          python-version: "3.10"
          auto-activate-base: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg espeak libsndfile1 fonts-noto-cjk fonts-noto-cjk-extra

      - name: Install Conda + pip deps in env
        run: |
          conda run -n base conda install -y numpy pip
          conda run -n base python -m pip install aeneas

      - name: Confirm Conda env info
        run: |
          conda info
          conda list
          conda env list
          conda run -n base which python
          conda run -n base python --version

      - name: Confirm FFmpeg
        run: ffmpeg -version

      - name: Run generator in Conda env
        run: conda run -n base python generate_video.py
