jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # ✅ 이거면 FFmpeg 기본 포함!
      - name: Confirm FFmpeg version
        run: ffmpeg -version

      - name: Install fonts
        run: sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra

      - name: Run video generator
        run: python generate_video.py
