name: Generate News Video

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg espeak libsndfile1 fonts-noto-cjk fonts-noto-cjk-extra

      - name: Install Python dependencies (Conda env)
        run: |
          conda install -y pip numpy
          conda list
          which python
          which pip
          python --version
          pip --version
          # ✅ Conda env 내 pip 실행 강제
          conda run -n base python -m pip install aeneas

      - name: Confirm Conda packages
        run: |
          conda list
          conda info

      - name: Confirm FFmpeg version
        run: ffmpeg -version

      - name: Run generator script (Conda env)
        run: |
          conda run -n base python generate_video.py
