name: Upload YouTube Shorts

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2-8 * * *" # 매일 2시~8시 매 정각
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run upload script
        run: |
          python upload_to_youtube.py
