name: Upload YouTube Shorts

on:
  # 오전 4시부터 10마다
  schedule:
    # 낮 12시~4시(KST) 10분마다
      - cron: "0 19-23 * * *"  # UTC 19~23시 (KST 4~8시)
      - cron: "0 0-15 * * *"   # UTC 0~15시 (KST 9~24시)

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run upload script
        run: |
          python upload_to_youtube.py
