name: Upload YouTube Shorts

on:
  push:
    branches:
      - main
  # 오전 10시부터 11시까지 10분마다 업로드
  schedule:
    - cron: "0 1 * * *"   # KST 10:00
    - cron: "10 1 * * *"  # KST 10:10
    - cron: "20 1 * * *"  # KST 10:20
    - cron: "30 1 * * *"  # KST 10:30
    - cron: "40 1 * * *"  # KST 10:40
    - cron: "50 1 * * *"  # KST 10:50
    - cron: "0 2 * * *"   # KST 11:00

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run upload script
        run: |
          python upload_to_youtube.py
