name: Upload YouTube Shorts

on:
  push:
    branches:
      - main
  # 오전 4시부터 10마다
  schedule:
    - cron: "0 19 * * *"   # KST 04:00
    - cron: "10 19 * * *"  # KST 04:10
    - cron: "20 19 * * *"  # KST 04:20
    - cron: "30 19 * * *"  # KST 04:30
    - cron: "40 19 * * *"  # KST 04:40
    - cron: "50 19 * * *"  # KST 04:50
    - cron: "0 20 * * *"   # KST 05:00

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run upload script
        run: |
          python upload_to_youtube.py
